# Generated by Django 5.2.9 on 2025-12-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_social_accounts'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='socialaccount',
            name='unique_social_account',
        ),
        migrations.RenameIndex(
            model_name='socialaccount',
            new_name='authenticat_user_id_f2c1e4_idx',
            old_name='authentication_user_id_platform_idx',
        ),
        migrations.RenameIndex(
            model_name='socialaccount',
            new_name='authenticat_platfor_0e3f15_idx',
            old_name='authentication_platform_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='socialpost',
            new_name='authenticat_user_id_3cd17e_idx',
            old_name='authentication_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='socialpost',
            new_name='authenticat_social__137998_idx',
            old_name='authentication_account_status_idx',
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('user', 'platform', 'platform_user_id')},
        ),
    ]
