# Generated by Django 5.2.9 on 2025-12-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0017_add_balance_before_to_credit_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clip',
            options={'ordering': ['-engagement_score', '-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='embeddingpattern',
            name='unique_org_pattern_name',
        ),
        migrations.RenameIndex(
            model_name='embeddingcache',
            new_name='clips_embed_text_ha_548901_idx',
            old_name='clips_embe_text_ha_idx',
        ),
        migrations.RenameIndex(
            model_name='embeddingcache',
            new_name='clips_embed_last_ac_b981f4_idx',
            old_name='clips_embe_last_ac_idx',
        ),
        migrations.RenameIndex(
            model_name='embeddingpattern',
            new_name='clips_embed_organiz_172c4d_idx',
            old_name='clips_embe_organiz_idx',
        ),
        migrations.RenameIndex(
            model_name='embeddingpattern',
            new_name='clips_embed_organiz_b2b1a9_idx',
            old_name='clips_embe_organiz_2_idx',
        ),
        migrations.AlterField(
            model_name='clip',
            name='engagement_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='embeddingpattern',
            unique_together={('organization', 'name')},
        ),
    ]
